# Generated by Django 6.1 on 2026-08-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_route_bus_seat_booking_delete_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
