# Generated by Django 5.1.9 on 2026-09-22 14:33

from django.db import migrations, models


def backfill_positions(apps, schema_editor):
    Bus = apps.get_model('accounts', 'Bus')
    for bus in Bus.objects.all():
        seats = list(bus.seats.all())
        ordered = sorted(
            seats,
            key=lambda s: (s.seat_number.isdigit(), int(s.seat_number)) if s.seat_number.isdigit() else (False, 10**9, s.id),
        )
        for position, seat in enumerate(ordered, start=1):
            seat.position = position
            seat.save(update_fields=['position'])


def reverse_positions(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_dedupe_profile_phone_numbers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AddField(
            model_name='seat',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_positions, reverse_positions),
    ]
